version: '3.4'

services:
  redis:
    image: redis
  webhooktester.presentation:
    image: ${DOCKER_REGISTRY}webhooktesterpresentation
    build:
      context: WebhookTester.Presentation
      dockerfile: Dockerfile
    enviroment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisHost=redis
      - RedisInstanceName=redis-cache
    depends_on: redis