version: '3.4'

services:
  redis:
    image: redis
  webhooktester.presentation:
    image: ${DOCKER_REGISTRY}webhooktesterpresentation
    build:
      context: .
      dockerfile: WebhookTester.Presentation/Dockerfile
    ports:
      - 8066:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisHost=redis
      - RedisInstanceName=redis-cache
    depends_on: 
      - redis